# Dive CI configuration for Change Reel Docker image analysis
# Used to analyze and optimize Docker image layers

rules:
  # Fail if image efficiency is below threshold
  lowestEfficiency: 0.95
  
  # Fail if image has too much wasted space
  highestWastedBytes: 50MB
  
  # Fail if a single layer has too much wasted space
  highestUserWastedPercent: 0.20

# Output configuration
output:
  # Format: json, table
  format: json
  
  # Show aggregated results
  aggregated: true
  
  # Show layer details
  details: true

# Analysis configuration
analysis:
  # Include file tree analysis
  file-tree: true
  
  # Include layer analysis
  layer-details: true
  
  # Include efficiency analysis
  efficiency: true 