version: '3.8'

services:
  change-reel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env.local  # Copy docker.env.template to .env.local and fill in your values
    restart: unless-stopped
    # Mount for development - comment out for production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
