version: '3.8'

services:
  change-reel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production  # Copy docker.env.template to .env.production and fill in production values
    restart: unless-stopped
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    # Production health check
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false  # Next.js needs write access for some runtime files
    tmpfs:
      - /tmp:noexec,nosuid,size=100m 