version: '3.8'

services:
  change-reel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-manual}
        LIGHTNINGCSS_FORCE_WASM: "1"
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
