version: '3.8'

services:
  wins-column:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
